# Generated by Django 3.2.7 on 2021-09-13 18:32

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=article.models.upload_image_to),
        ),
    ]
