# Generated by Django 3.2.7 on 2021-09-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JPNikkei225',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(unique_for_date=True)),
                ('open', models.FloatField(default='')),
                ('close', models.FloatField(default='')),
                ('max', models.FloatField(default='')),
                ('min', models.FloatField(default='')),
                ('volume', models.IntegerField(default='')),
                ('price', models.FloatField(default='')),
            ],
        ),
    ]
