# Generated by Django 3.2.7 on 2021-09-15 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_jpnikkei225_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jpnikkei225',
            name='id',
        ),
        migrations.AddField(
            model_name='jpnikkei225',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique_for_date=True),
            preserve_default=False,
        ),
    ]
