# Generated by Django 3.2.7 on 2021-09-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210915_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jpnikkei225',
            old_name='max',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='jpnikkei225',
            old_name='min',
            new_name='low',
        ),
    ]
